SCREEN_WIDTH            = 800
SCREEN_HEIGHT           = 600
SCREEN_TITLE            = "Space Invaders"
TAMANHO_DA_NAVE         = 0.7
TAMANHO_DA_NAVE_INIMIGA = 0.2
RODAR_JOGO              = 6
GAME_OVER               = 7
VELOCIDADE_DO_TIRO      = 4
TAMANHO_DO_TIRO         = 0.8 
MOVIMENTACAO_DA_NAVE    = 7